language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - "pip install pep8 pyflakes coveralls"

script:
  - "python setup.py test"
  - "pep8 flask_jsonpify.py"

after_success:
  - "coveralls"